### ISSUE TITLE
Jokers that give money or other items at the end of the round does not work.

### ISSUE THREAD

**Issue by L0m** [Dimserene/Dimserenes-Modpack#3]
Things like Golden Joker, Cloud Nine, Rocket, Delayed Gratification etc. simple useless in this modpack now.
Any idea on which mod causes this or how to fix it?

**Comment by Dimserene** [comment]
Fusion jokers is causing this. For now you can simply remove it (and it's submod jestobiology)

**Comment by L0m** [comment]
But I love Fusion jokers... Is it possible to fix code? So both works.

**Comment by Dimserene** [comment]
I don't think the mod author still maintain the mod (at least not until the smods' official release)

**Comment by L0m** [comment]
Is it possible to make a fork with needed fixes? I'm not so familiar with lua, but if you know the issue it probably not that hard?
I can give it a shot myself, but I lack experience. If you can provide some pointers I'll try it.

**Comment by Dimserene** [comment]
Sorry, for now it's remove or withstand. Maybe there exist fixes out there, but I haven't seen them.

**Comment by Dimserene** [comment]
The mods Fusion Jokers and Jestobiology are re-added since this issue is solved by @gaycoonie.
