### ISSUE TITLE
ro-balatro fails to download

### ISSUE THREAD

**Issue by jmars125** [Dimserene/Dimserenes-Modpack#4]
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Dimserene/Ro-Balatro.git' into submodule path 'C:/Users/Administrator/AppData/Roaming/Balatro/Dimserenes-Modpack/Mods/Ro-Balatro' failed
Failed to clone 'Mods/Ro-Balatro'. Retry scheduled
Cloning into 'C:/Users/Administrator/AppData/Roaming/Balatro/Dimserenes-Modpack/Mods/Ro-Balatro'...
Host key verification failed.
fatal: Could not read from remote repository.

**Comment by Dimserene** [comment]
It should be fixed. Please try again and let me know if it's good again!

**Comment by jmars125** [comment]
Yes it has been resolved now thank you!
