### ISSUE TITLE
After Downloading setup.bat and running it you will encounter the following error

### ISSUE THREAD

**Issue by jmars125** [Dimserene/Dimserenes-Modpack#5]
Error

Syntax error: card.lua:5119: 'end' expected (to close 'if' at line 5112) near 'else'

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: at 0x7ff8d43d2fa0
[C]: in function 'require'
main.lua:27: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

![image](https://github.com/user-attachments/assets/cce9ab16-1ee3-4cb6-a133-87c9b1aacc6f)

INFO - [G] Error: Syntax error: card.lua:5119: 'end' expected (to close 'if' at line 5112) near 'else'

stack traceback:
        [love "boot.lua"]:352: in function <[love "boot.lua"]:348>
        [C]: at 0x7ff8d43d2fa0
        [C]: in function 'require'
        main.lua:27: in main chunk
        [C]: in function 'require'
        [love "boot.lua"]:323: in function <[love "boot.lua"]:126>
        [C]: in function 'xpcall'
        [love "boot.lua"]:362: in function <[love "boot.lua"]:355>
        [C]: in function 'xpcall'

**Comment by Dimserene** [comment]
This one belongs to Bunco. Before Firch fixes this I suggest you remove Bunco temporarily.

**Comment by Dimserene** [comment]
Fixed in the updated version.
