### ISSUE TITLE
Dimserenes Modpack not working with Deck Creator

### ISSUE THREAD

**Issue by BalatroUser69** [Dimserene/Dimserenes-Modpack#6]
↓Crash report below↓

Oops! The game crashed:
Mods/Deck Creator/GUI.lua:1697: attempt to call field 'registerUIElement' (a nil value)

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0-ALPHA-0721a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Dimserene's Modpack Utility by Dimserene [ID: Modpack_Util, Priority: -1e+24, Version: Full(Extreme)]
    2: Easier Scoring by Cerlo [ID: EasierScoring, Priority: -10000000000000, Version: snapshot24w28d]
    3: Loop by jenwalter666 [ID: loop, Priority: -9999999999, Version: 0.1.1]
    4: Phantom Thieves by Cerlo [ID: PhantomThieves, Priority: -1000000, Version: 0.3.3]
    5: JokerDisplay by nh6574 [ID: JokerDisplay, Priority: -100000, Version: 1.6.1]
    6: Joker Evolution by SDM_0 [ID: joker_evolution, Priority: -1000, Version: 1.0.1c]
    7: D6 Jokers by ItsFlowwey [ID: D6Joker, Priority: -900, Version: 0.5.31]
    8: Betmma Vouchers by Betmma [ID: BetmmaVouchers, Priority: -1, Version: 2.2.0-alpha(20240717)]
    9: Deck Creator by Nyoxide [ID: ADeckCreatorModule]

Stack Traceback
===============
(3) Lua field 'registerModMenuUI' at file 'Mods/Deck Creator/GUI.lua:1697'
Local variables:
 (*temporary) = nil
 (*temporary) = string: "ADeckCreatorModule"
 (*temporary) = table: 0x2b199288  {1:table: 0x2b0f2558, 2:table: 0x2b018dc8, 3:table: 0x2a6fe410, 4:table: 0x2b02ae50 (more...)}
 (*temporary) = string: "attempt to call field 'registerUIElement' (a nil value)"
(4) Lua field 'Enable' at file 'Mods/Deck Creator/DeckCreator.lua:21'
(5) Lua local 'v' at file 'ADeckCreatorModule.lua:61' (from mod with id ADeckCreatorModule)
Local variables:
 Loader = table: 0x2ac4e910  {BalamodLoaded:false, SteamoddedLoaded:true, DeckCreatorLoader:true}
(6) Lua local 'func' at Steamodded file 'loader/loader.lua:254' 
Local variables:
 (for generator) = C function: next
 (for state) = table: 0x2ac497a0  {DeckCreatorModule:function: 0x2ac4e6b8}
 (for control) = number: nan
 k = string: "DeckCreatorModule"
 v = Lua function '?' (defined at line 56 of chunk [SMODS ADeckCreatorModule "ADeckCreatorModule.lua"])
(7) Lua field 'with_compat' at Steamodded file 'core/compat_0_9_8.lua:522' 
Local variables:
 func = Lua function '?' (defined at line 250 of chunk [SMODS _ "loader/loader.lua"])
 localization_ref = table: 0x2a840730  {tutorial_parsed:table: 0x2b119360, UI:table: 0x2a75e1d8, misc:table: 0x2a75e228 (more...)}
 captured_loc = table: 0x2ac4b7b0  {}
(8) Lua global 'loadMods' at Steamodded file 'loader/loader.lua:250' 
Local variables:
 modsDirectory = string: "C:\\Users\\luke\\AppData\\Roaming\\Balatro\\Mods"
 header_components = table: 0x2ad18bc0  {conflicts:table: 0x2ad19648, outdated:table: 0x2ad198d8, version:table: 0x2ad19758 (more...)}
 used_prefixes = table: 0x2ad19a10  {infa:Infarctus_Ante_scaling_linear, myst:MystBlinds, modp:Modpack_Util (more...)}
 processDirectory = Lua function '?' (defined at line 68 of chunk [SMODS _ "loader/loader.lua"])
 keyset = table: 0x2a9cda60  {1:-1e+24, 2:-10000000000000, 3:-9999999999, 4:-1000000, 5:-100000, 6:-1000 (more...)}
 check_dependencies = Lua function '?' (defined at line 178 of chunk [SMODS _ "loader/loader.lua"])
 (for generator) = C function: builtin#6
 (for state) = table: 0x2a9cda60  {1:-1e+24, 2:-10000000000000, 3:-9999999999, 4:-1000000, 5:-100000, 6:-1000 (more...)}
 (for control) = number: 9
 _ = number: 9
 priority = number: 0
 (for generator) = C function: builtin#6
 (for state) = table: 0x2ad1f830  {1:table: 0x2acb40a0, 2:table: 0x2a851b78, 3:table: 0x2a97ed40, 4:table: 0x2ad9de58 (more...)}
 (for control) = number: 1
 _ = number: 1
 mod = table: 0x2acb40a0  {version:0.0.0, id:ADeckCreatorModule, main_file:ADeckCreatorModule.lua (more...)}
(9) Lua global 'initSteamodded' at Steamodded file 'loader/loader.lua:337' 
(10) Lua upvalue 'su' at file 'game.lua:315'
Local variables:
 self = table: 0x2a538c90  {PALETTE:table: 0x2a998590, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1f-FULL\",[\"reduced_motion\"]=false,[\"paused\"]=false,[\"QUEUED_CHANGE\"]={},[\"screenshake\"]=50,[\"colourblind_option\"]=false,[\"play_button_pos\"]=1,[\"profile\"]=3,[\"selected_colours\"]={[\"Spectral\"]={[\"order\"]=1,[\"old_colours\"]={},[\"name\"]=\"Default\",[\"new_colours\"]={},},[\"Tarot\"]={[\"order\"]=1,[\"old_colours\"]={},[\"name\"]=\"Default\",[\"new_colours\"]={},},[\"Planet\"]={[\"order\"]=1,[\"old_colours\"]={},[\"name\"]=\"Default\",[\"new_colours\"]={},},[\"Suits\"]={[\"order\"]=1,[\"old_colours\"]={[4]={[4]=1,[1]=0.94117647058824,[2]=0.20392156862745,[3]=0.3921568627451,},[1]={[4]=1,[1]=0.13725490196078,[2]=0.34901960784314,[3]=0.33333333333333,},[2]={[4]=1,[1]=0.23529411764706,[2]=0.26274509803922,[3]=0.4078431372549,},[3]={[4]=1,[1]=0.94117647058824,[2]=0.41960784313725,[3]=0.24705882352941,},},[\"name\"]=\"Default\",[\"new_colours\"]={[4]={[4]=1,[1]=0.94117647058824,[2]=0.20392156862745,[3]=0.3921568627451,},[1]={[4]=1,[1]=0.13725490196078,[2]=0.34901960784314,[3]=0.33333333333333,},[2]={[4]=1,[1]=0.23529411764706,[2]=0.26274509803922,[3]=0.4078431372549,},[3]={[4]=1,[1]=0.94117647058824,[2]=0.41960784313725,[3]=0.24705882352941,},},},},[\"crashreports\"]=true,[\"language\"]=\"en-us\",[\"WINDOW\"]={[\"vsync\"]=1,[\"display_names\"]={[1]=\"1\",},[\"screenmode\"]=\"Borderless\",[\"DISPLAYS\"]={[1]={[\"screen_resolutions\"]={[\"strings\"]={[1]=\"2560 X 1440\",},[\"values\"]={[1]={[\"w\"]=1920,[\"h\"]=1080,},},},[\"screen_res\"]={[\"w\"]=2560,[\"h\"]=1440,},[\"DPI_scale\"]=1,[\"MONITOR_DIMS\"]={[\"height\"]=1440,[\"width\"]=2560,},},},[\"selected_display\"]=1,},[\"tutorial_complete\"]=true,[\"GAMESPEED\"]=999,[\"SOUND\"]={[\"volume\"]=0,[\"music_volume\"]=0,[\"game_sounds_volume\"]=0,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"ante_upper\"]=true,[\"royale\"]=true,[\"_1000k\"]=true,[\"_10k\"]=true,[\"retrograde\"]=true,[\"ante_up\"]=true,[\"heads_up\"]=true,},[\"COMP\"]={[\"score\"]=9.4347073726272e+194,[\"name\"]=\"\",[\"prev_name\"]=\"\",},[\"current_setup\"]=\"New Run\",[\"ambient_control\"]={[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=0,},[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=0,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=0,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=0,},},[\"no_mod_tracking\"]=false,[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=40.162009625054,},[\"GRAPHICS\"]={[\"texture_scaling\"]=2,[\"crt\"]=50.332167356216,[\"bloom\"]=1,[\"shadows\"]=\"On\",},}"
 settings_ver = nil
 new_colour_proto = table: 0x2a58c318  {Spades:table: 0x2a53ecf0, Hearts:table: 0x2a58c3f0, Diamonds:table: 0x2a58c4a8 (more...)}
 sound_files = table: 0x2aa31ed8  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
 shader_files = table: 0x2a8d1978  {1:CRT.fs, 2:background.fs, 3:booster.fs, 4:debuff.fs, 5:dissolve.fs, 6:flame.fs (more...)}
(11) Lua method 'start_up' at file 'main.lua:1827'
Local variables:
 self = table: 0x2a538c90  {PALETTE:table: 0x2a998590, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
(12) Lua field 'load' at file 'main.lua:879'
(13) Lua function '?' at file 'main.lua:826' (best guess)
(14) global C function 'xpcall'
(15) Love2D function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(16) global C function 'xpcall'
(17) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by Dimserene** [comment]
Yes I am aware of that, and that is why we don't include it now
