### ISSUE TITLE
Crash on boot w/ fresh install + Your Discord links are broken

### ISSUE THREAD

**Issue by luxidoptera** [Dimserene/Dimserenes-Modpack#7]
Oops! The game crashed:
Syntax error: tag.lua:205: 'end' expected (to close 'if' at line 203) near 'elselocal'

Additional Context:
Balatro Version: ???
Modded Version: ???
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6

Stack Traceback
===============
(3)  C function 'function: 0x04b6ced8'
(4) global C function 'require'
(5) main chunk of file 'main.lua' at line 1751
(6) global C function 'require'
(7) Love2D function at file 'boot.lua:323' (best guess)
Local variables:
 c = table: 0x04b6e138  {identity:false, version:11.5, accelerometerjoystick:true, modules:table: 0x04b6e160 (more...)}
 openedconsole = boolean: false
 confok = boolean: true
 conferr = nil
(8) global C function 'xpcall'
(9) Love2D function at file 'boot.lua:362' (best guess)
Local variables:
 result = boolean: true
(10) global C function 'xpcall'
(11) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

---

Also, your Discord links don't work. They're not invite links, and thus just try to direct a user to a channel they don't have access to.

**Comment by Dimserene** [comment]
Thanks for the report, I've added the invitation link to Balatro official discord. 
The boot crash is not happening for me. Can you try again and let me know if it's still a problem?

**Comment by luxidoptera** [comment]
Still happening. Could it have anything to do with me having installed Steamodded before I knew about this pack?

**Comment by Dimserene** [comment]
you actually don't need to install smods yourself. the modpack will install and update smods for you

**Comment by luxidoptera** [comment]
I know- I'd installed it prior to finding out this pack existed, and figured it would probably be fine. I'm asking if that's a possible issue here.

**Comment by luxidoptera** [comment]
Update: as it turns out this _was_ the problem. The modpack can't tell if you have Steamodded installed already (understandable given it's just a batch file), and as a result I had two copies of the modloader which weren't playing nice. I don't know why I didn't think to check that.

**Comment by Dimserene** [comment]
may i ask some question: if you didn't have the access of official balatro discord, how did you find my modpack?

**Comment by luxidoptera** [comment]
SUPER late but a friend of mine recommended it to me
