### ISSUE TITLE
Game crash on start up    halp plz :,<

### ISSUE THREAD

**Issue by BalatroUser69** [Dimserene/Dimserenes-Modpack#8]
Oops! The game crashed:
Syntax error: functions/state_events.lua:434: unexpected symbol near '}'

Failed to get additional context :/

Stack Traceback
===============
(3)  C function 'function: 0x21ccaf48'
(4) global C function 'require'
(5) main chunk of file 'main.lua' at line 958
(6) global C function 'require'
(7) Love2D function at file 'boot.lua:323' (best guess)
Local variables:
 c = table: 0x21cb9538  {identity:false, version:11.5, accelerometerjoystick:true, modules:table: 0x21cb9588 (more...)}
 openedconsole = boolean: false
 confok = boolean: true
 conferr = nil
(8) global C function 'xpcall'
(9) Love2D function at file 'boot.lua:362' (best guess)
Local variables:
 result = boolean: true
(10) global C function 'xpcall'
(11) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by Dimserene** [comment]
If you can please reach out on discord, where we can get this to solve quickly
